feat: avoid use hard-coded version
Signed-off-by: Jeffrey Tang <jeffrey@swirldslabs.com>

diff --git a/.github/workflows/flow-migration-test.yaml b/.github/workflows/flow-migration-test.yaml
--- a/.github/workflows/flow-migration-test.yaml
+++ b/.github/workflows/flow-migration-test.yaml
@@ -39,8 +39,6 @@ jobs:
     runs-on: hiero-solo-linux-large
     strategy:
       fail-fast: false
-      matrix:
-        release-tag: ["0.41.0"]
     steps:
       - name: Harden Runner
         uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
@@ -77,7 +75,7 @@ jobs:
           version: 'v1.27.3'
         id: install
 
-      - name: Launch Network with Prior Release ${{ matrix.release-tag }}
+      - name: Launch Network with Prior Release $LATEST_VERSION
         timeout-minutes: 60
         run: |
           echo "Install yq..."
@@ -87,9 +85,11 @@ jobs:
   
           npm install
           task build
-          timeout --kill-after=1s --preserve-status 55m bash -c '.github/workflows/script/launch_network.sh ${{ matrix.release-tag }}' || RC=$? || true
+          LATEST_VERSION=$(curl -s https://registry.npmjs.org/@hashgraph/solo/latest | jq -r '.version')
+          echo "Latest Version: ${LATEST_VERSION}"
+          timeout --kill-after=1s --preserve-status 55m bash -c '.github/workflows/script/launch_network.sh $LATEST_VERSION' || RC=$? || true
           if [[ "$RC" != "0" ]]; then
-            echo "Failed to launch network with release version ${{ matrix.release-tag }}"
+            echo "Failed to launch network with release version $LATEST_VERSION"
             exit $RC
           fi
 
