fix
Signed-off-by: Jeffrey Tang <jeffrey@swirldslabs.com>

diff --git a/.github/workflows/flow-migration-test.yaml b/.github/workflows/flow-migration-test.yaml
--- a/.github/workflows/flow-migration-test.yaml
+++ b/.github/workflows/flow-migration-test.yaml
@@ -176,9 +176,9 @@ jobs:
           trap - SIGTERM SIGINT
 
           if [[ "$RC" != "0" ]]; then
-              echo "Failed to launch network with release version ${{ steps.get-version.outputs.from_solo_version }}"
-              exit $RC
-            fi
+            echo "Failed to launch network with release version ${{ steps.get-version.outputs.from_solo_version }}"
+            exit $RC
+          fi
 
       - name: Collect Deployment Diagnostics Logs
         if: ${{ !cancelled() && always() }}
