ci(dual-publish): Update publish workflows
Signed-off-by: Roger Barker <roger.barker@swirldslabs.com>

diff --git a/.github/workflows/flow-deploy-release-artifact.yaml b/.github/workflows/flow-deploy-release-artifact.yaml
--- a/.github/workflows/flow-deploy-release-artifact.yaml
+++ b/.github/workflows/flow-deploy-release-artifact.yaml
@@ -23,9 +23,16 @@ on:
         type: boolean
         required: false
         default: true
+      dual-publish-enabled:
+        description: "Dual Publish Enabled"
+        type: boolean
+        required: false
+        default: false
 
 env:
   REGISTRY: ghcr.io
+  HASHGRAPH_PKG_NAME: "@hashgraph/solo"
+  HIERO_PKG_NAME: "@hiero-ledger/solo"
 
 defaults:
   run:
@@ -45,7 +52,8 @@ jobs:
     runs-on: hiero-solo-linux-medium
     outputs:
       version: ${{ steps.set-outputs.outputs.version }}
-      need-release: ${{ steps.set-outputs.outputs.need-release }}
+      need-hg-release: ${{ steps.set-outputs.outputs.need-hg-release }}
+      need-hl-release: ${{ steps.check-hl-release-needed.outputs.need-hl-release }}
     steps:
       - name: Harden the runner (Audit all outbound calls)
         uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
@@ -107,7 +115,7 @@ jobs:
             fi
           fi
 
-          echo "need-release=${PROCEED}" >> "${GITHUB_OUTPUT}"
+          echo "need-hg-release=${PROCEED}" >> "${GITHUB_OUTPUT}"
 
       - name: Extract Version
         id: set-outputs
@@ -130,7 +138,18 @@ jobs:
           fi
 
           echo "version=${OUTVER}" >> "${GITHUB_OUTPUT}"
-          echo "need-release=${PROCEED}" >> "${GITHUB_OUTPUT}"
+          echo "need-hg-release=${PROCEED}" >> "${GITHUB_OUTPUT}"
+
+      - name: "Check: HL release needed"
+        id: check-hl-release-needed
+        if: ${{ steps.set-outputs.outputs.need-release == 'true' && inputs.dual-publish-enabled == true }}
+        run: |
+          PUBLISH_REQUIRED="false"
+          if ! curl -sSLf "https://registry.npmjs.org/${{ env.HIERO_PKG_NAME }}/${{ steps.set-outputs.outputs.version }}" >/dev/null 2>&1; then
+            PUBLISH_REQUIRED="true"
+          fi
+          
+          echo "need-hl-release=${PUBLISH_REQUIRED}" >> "${GITHUB_OUTPUT}"
 
   get-package-info:
     name: 'Get Package Info'
@@ -139,7 +158,8 @@ jobs:
     needs:
       - prepare-release
     outputs:
-      package-name: ${{ steps.set-package-name.outputs.package-name }}
+      hg-package-name: ${{ steps.set-hg-package-name.outputs.hg-package-name }}
+      hl-package-name: ${{ steps.set-hl-package-name.outputs.hl-package-name }}
     steps:
       - name: Harden the runner (Audit all outbound calls)
         uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
@@ -160,24 +180,40 @@ jobs:
           version: 1.7
 
       - name: Generate Package name
-        id: set-package-name
+        id: set-hg-package-name
         run: |
           clean_pkg_name() {
             echo "${1}" | sed 's/^@//; s/\//-/g'
           }
           pname=$(jq -r '.name' './package.json')
+          if [[ "${pname}" != "${{ env.HASHGRAPH_PKG_NAME }}" ]]; then
+            echo "::error file=flow-deploy-release-artifact.yaml::Package name in package.json does not match expected package name '${{ env.HASHGRAPH_PKG_NAME }}'"
+            exit 1
+          fi
           full_pname=$(clean_pkg_name "${pname}-${{ needs.prepare-release.outputs.version }}.tgz")
-          echo "package-name=${full_pname}" | tee -a "${GITHUB_OUTPUT}"
+          echo "hg-package-name=${full_pname}" | tee -a "${GITHUB_OUTPUT}"
+
+      - name: Generate HL Package name
+        id: set-hl-package-name
+        if: ${{ inputs.dual-publish-enabled == true }}
+        run: |
+          clean_pkg_name() {
+            echo "${1}" | sed 's/^@//; s/\//-/g'
+          }
+          pname="${{ env.HIERO_PKG_NAME }}"
+          full_pname=$(clean_pkg_name "${pname}-${{ needs.prepare-release.outputs.version }}.tgz")
+          echo "hl-package-name=${full_pname}" | tee -a "${GITHUB_OUTPUT}"
 
   create-github-release:
     name: 'Create GitHub Release'
     runs-on: hiero-solo-linux-medium
-    if: ${{ needs.prepare-release.outputs.need-release == 'true' }}
+    if: ${{ needs.prepare-release.outputs.need-hg-release == 'true' || needs.prepare-release.outputs.need-hl-release == 'true' }}
     needs:
       - prepare-release
       - get-package-info
     outputs:
-      need-publish: ${{ steps.verify-package.outputs.need-publish }}
+      need-hg-publish: ${{ steps.verify-package.outputs.need-hg-publish }}
+      need-hl-publish: ${{ steps.verify-package.outputs.need-hl-publish }}
     steps:
       - name: Harden the runner (Audit all outbound calls)
         uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
@@ -316,6 +352,7 @@ jobs:
           echo "Example assets created and uploaded to release."
 
       - name: Create NPM Package
+        if: ${{ needs.prepare-release.outputs.need-hg-release == 'true' }}
         run: |
           echo "::group::View Version to publish to npm"
             echo "Version to publish:"
@@ -329,49 +366,107 @@ jobs:
           echo "::group::Create Package"
             FLAGS=""
             if [[ "${{ inputs.dry-run-enabled }}" == "true" ]]; then
-              echo "Command: npm pack --pack-destination \"output\""
+              echo "Command: npm pack --pack-destination \"output/hg\""
               FLAGS="--dry-run"
             fi
-            mkdir -p "output"
-            npm pack --pack-destination "output" ${FLAGS}
+            mkdir -p "output/hg"
+            npm pack --pack-destination "output/hg" ${FLAGS}
           echo "::endgroup::"
 
       - name: Verify Package is Created
         id: verify-package
+        if: ${{ needs.prepare-release.outputs.need-hg-release == 'true' }}
         run: |
           PROCEED="true"
           echo "::group::Verify Package is Created"
-            if ls -l output | grep "${{ needs.get-package-info.outputs.package-name }}" > /dev/null 2>&1 ; then
-              echo "::notice file=flow-deploy-release-artifact.yaml::Package is created"
+            if ls -l output | grep "${{ needs.get-package-info.outputs.hg-package-name }}" > /dev/null 2>&1 ; then
+              echo "::notice file=flow-deploy-release-artifact.yaml::HG Package is created"
             else
               PROCEED="false"
-              echo "::error file=flow-deploy-release-artifact.yaml::Package is not created"
+              echo "::error file=flow-deploy-release-artifact.yaml::HG Package is not created"
               echo "Attempt Manual Publish!"
             fi
           echo "::endgroup::"
-          echo "need-publish=${PROCEED}" >> "${GITHUB_OUTPUT}"
+          echo "need-hg-publish=${PROCEED}" >> "${GITHUB_OUTPUT}"
 
-      - name: Upload Package
-        if: ${{ steps.verify-package.outputs.need-publish == 'true' }}
+      - name: Upload HG Package
+        if: ${{ needs.prepare-release.outputs.need-hg-release && steps.verify-package.outputs.need-hg-publish == 'true' }}
         uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
         with:
-          name: npm-package
-          path: output
+          name: npm-hg-package
+          path: output/hg
           if-no-files-found: error
 
-  publish-npm-package:
+      - name: Update Files for Dual Publish
+        id: update-for-dual-publish
+        if: ${{ inputs.dual-publish-enabled == true && needs.prepare-release.outputs.needs-hl-release == 'true' }}
+        run: |
+          echo "::group::Update package.json files for dual publish"
+          files=("package.json")
+          for file in "${files[@]}"; do
+            if [[ -f "$file" ]]; then
+              cp "$file" "$file.tmp"
+              jq '.name |= sub("@hashgraph/solo";"@hiero-ledger/solo")' "$file.tmp" > "$file"
+            else
+              echo "::warning::File $file does not exist, skipping update."
+            fi
+          done
+          
+          find . -type f -name "*.js" -exec sed -i "s/\b@hashgraph\/solo\b/@hiero-ledger\/solo/g" {} +
+          npm install
+          task build
+          echo "::endgroup::"
+          echo "::group::View Version to publish to npm"
+            echo "Version to publish:"
+            cat package.json | grep 'version'
+          echo "::endgroup::"
+          
+          echo "::group::Install dependencies"
+          npm install
+          echo "::endgroup::"
+
+          echo "::group::Build HL NPM Package"
+          task build
+          echo "::endgroup::"
+
+          echo "::group::Create HL Package"
+            FLAGS=""
+            if [[ "${{ inputs.dry-run-enabled }}" == "true" ]]; then
+              echo "Command: npm pack --pack-destination \"output/hl\""
+              FLAGS="--dry-run"
+            fi
+            mkdir -p "output/hl"
+            npm pack --pack-destination "output/hl" ${FLAGS}
+          echo "::endgroup::"
+          
+          PROCEED="true"
+          echo "::group::Verify HL Package is Created"
+            if ls -l output | grep "${{ needs.get-package-info.outputs.hl-package-name }}" > /dev/null 2>&1 ; then
+              echo "::notice file=flow-deploy-release-artifact.yaml::HL Package is created"
+            else
+              PROCEED="false"
+              echo "::error file=flow-deploy-release-artifact.yaml::HL Package is not created"
+              echo "Attempt Manual Publish!"
+            fi
+          echo "::endgroup::"
+          echo "need-hl-publish=${PROCEED}" >> "${GITHUB_OUTPUT}"
+
+      - name: Upload HL Package
+        if: ${{ inputs.dual-publish-enabled == true && needs.prepare-release.outputs.need-hl-release && steps.update-for-dual-publish.outputs.need-hl-publish == 'true' }}
+        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
+        with:
+          name: npm-hl-package
+          path: output/hl
+          if-no-files-found: error
+
+  publish-npm-packages:
     name: Publish Release packages
     runs-on: ubuntu-latest
     needs:
       - get-package-info
       - create-github-release
-    if: ${{ needs.create-github-release.outputs.need-publish == 'true' || inputs.dry-run-enabled == true }}
+    if: ${{ needs.create-github-release.outputs.need-hg-publish == 'true' || needs.create-github-release.outputs.need-hl-publish || inputs.dry-run-enabled == true }}
     steps:
-      - name: Harden the runner (Audit all outbound calls)
-        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
-        with:
-          egress-policy: audit
-
       - name: Prepare Job
         uses: pandaswhocode/initialize-github-job@a57cd6d8d768b2f3c95334bdd4fa8c21609fc651 # 1.0.5
         with:
@@ -385,12 +480,19 @@ jobs:
       - name: Install NPM latest
         run: npm install -g npm@11.7.0
 
-      - name: Download NPM Package Artifact
-        if: ${{ inputs.dry-run-enabled != true }}
+      - name: Download HG NPM Package Artifact
+        if: ${{ needs.create-github-release.outputs.need-hg-publish == 'true' && inputs.dry-run-enabled != true }}
         uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
         with:
-          name: npm-package
-          path: output
+          name: npm-hg-package
+          path: output/hg
+
+      - name: Download HL NPM Package Artifact
+        if: ${{ needs.create-github-release.outputs.need-hl-publish == 'true' && inputs.dry-run-enabled != true }}
+        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
+        with:
+          name: npm-hl-package
+          path: output/hl
 
       - name: Install Task
         uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
@@ -398,7 +500,8 @@ jobs:
           version: 3.39.2
           repo-token: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Publish NPM Package
+      - name: Publish HG NPM Package
+        if: ${{ needs.create-github-release.outputs.need-hg-publish == 'true' || inputs.dry-run-enabled == true }}
         run: |
           echo "::group::Set Publish Args"
             FLAGS="--access=public"
@@ -406,7 +509,7 @@ jobs:
           echo "::endgroup::"
 
           echo "::group::Set tarball output"
-            TARBALL="./output/${{ needs.get-package-info.outputs.package-name }}"
+            TARBALL="./output/hg/${{ needs.get-package-info.outputs.hg-package-name }}"
             if [[ "${{ inputs.dry-run-enabled }}" == "true" ]]; then
               TARBALL=""
             fi
@@ -414,6 +517,28 @@ jobs:
           echo "::endgroup::"
 
           echo "::group::Publish NPM Package"
+            if [[ "${{ inputs.dry-run-enabled }}" != "true" ]]; then
+              npm publish ${TARBALL} ${FLAGS}
+            fi
+          echo "::endgroup::"
+
+      - name: Publish HL NPM Package
+        if: ${{ inputs.dual-publish-enabled == true && needs.create-github-release.outputs.need-hl-publish == 'true' || inputs.dry-run-enabled == true }}
+        run: |
+          echo "::group::Set Publish Args"
+            FLAGS="--access=public"
+            echo "flags=${FLAGS}"
+          echo "::endgroup::"
+
+          echo "::group::Set tarball output"
+            TARBALL="./output/hl/${{ needs.get-package-info.outputs.hl-package-name }}"
+            if [[ "${{ inputs.dry-run-enabled }}" == "true" ]]; then
+              TARBALL=""
+            fi
+            echo "tarball=${TARBALL}"
+          echo "::endgroup::"
+
+          echo "::group::Publish HL NPM Package"
             if [[ "${{ inputs.dry-run-enabled }}" != "true" ]]; then
               npm publish ${TARBALL} ${FLAGS}
             fi
