save
Signed-off-by: Jeffrey Tang <jeffrey@swirldslabs.com>

diff --git a/.github/workflows/flow-migration-test.yaml b/.github/workflows/flow-migration-test.yaml
--- a/.github/workflows/flow-migration-test.yaml
+++ b/.github/workflows/flow-migration-test.yaml
@@ -75,7 +75,14 @@ jobs:
           version: 'v1.27.3'
         id: install
 
-      - name: Launch Network with Prior Release $LATEST_VERSION
+      - name: Get Latest Version
+        id: get-version
+        run: |
+          LATEST_VERSION=$(curl -s https://registry.npmjs.org/@hashgraph/solo/latest | jq -r '.version')
+          echo "Latest Version: ${LATEST_VERSION}"
+          echo "version=${LATEST_VERSION}" >> $GITHUB_OUTPUT
+
+      - name: Launch Network with Prior Release ${{ steps.get-version.outputs.version }}
         timeout-minutes: 60
         run: |
           echo "Install yq..."
@@ -85,11 +92,9 @@ jobs:
   
           npm install
           task build
-          LATEST_VERSION=$(curl -s https://registry.npmjs.org/@hashgraph/solo/latest | jq -r '.version')
-          echo "Latest Version: ${LATEST_VERSION}"
-          timeout --kill-after=1s --preserve-status 55m bash -c '.github/workflows/script/launch_network.sh $LATEST_VERSION' || RC=$? || true
+          timeout --kill-after=1s --preserve-status 55m bash -c '.github/workflows/script/launch_network.sh ${{ steps.get-version.outputs.version }}' || RC=$? || true
           if [[ "$RC" != "0" ]]; then
-            echo "Failed to launch network with release version $LATEST_VERSION"
+            echo "Failed to launch network with release version ${{ steps.get-version.outputs.version }}"
             exit $RC
           fi
 
